_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 50
learning_rate:
    value: 0.002
num_workers:
    value: 10
patience:
    value: 8
rotation:
    value: 5
shear_angle:
    value: 1
translation:
    value: 0.1
